config/routes.rb
Rails.application.routes.draw do

  resources :tasks, except: [:destroy, :edit, :show]

  #get '/tasks', to: "tasks#index"

  #get '/tasks/new', to: "tasks#new"


  #get '/tasks/:id', to: "tasks#show", as: :task


  #post '/tasks', to: "tasks#create"


  get '/tasks/:id/edit', to: "tasks#edit", as: :edit_task
  #patch '/tasks/:id', to: "tasks#update"


  delete '/tasks/:id', to: "tasks#destroy", as: :destroy_task

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  def formatted_done
    if self.done
      "FAIT"
    else
      "PAS FAIT"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    #@task = Task.new(name: params[:task][:name], description: params[:task][:description])
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    #@task.update(name: params[:task][:name], description: params[:task][:description], done: params[:task][:done])

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:name, :description, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :done %>
  <%= f.check_box :done %>

  <%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit your task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Your TO DO list</h1>
<ul> <% @tasks.each do |task|%>
  <li><%= link_to(task.name, task_path(task)) %> - <%= task.formatted_done %>
    <%=link_to("Edit task", edit_task_path(task))%>
    <%=link_to("Delete", destroy_task_path(task), method: :delete)%>
  </li>
  <%end%>
</ul>

<%=link_to("Create new task", new_task_path)%>

app/views/tasks/new.html.erb
<h1>Créer une nouvelle tache</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Plus de détails</h1>

<h2><%=@task.name%></h2>
<p><%= @task.description%></p>
<p><%=@task.formatted_done%></p>

<%= link_to("Back to index", tasks_path)%>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>